#include "canimal.h"

CAnimal::CAnimal(QString path)
    : CZTUnit(path)
{
    m_config[charInts]["cBoxFootprintX"] = "";
    m_config[charInts]["cBoxFootprintY"] = "";
    m_config[charInts]["cBoxFootprintZ"] = "";
    m_config[charInts]["cFamily"] = "";
    m_config[charInts]["cGenus"] = "";
    m_config[charInts]["cHabitat"] = "";
    m_config[charInts]["cLocation"] = "";
    m_config[charInts]["cEra"] = "";
    m_config[charInts]["cBreathThreshold"] = "";
    m_config[charInts]["cBreathIncrement"] = "";
    m_config[charInts]["cHungerThreshold"] = "";
    m_config[charInts]["cHungryHealthChange"] = "";
    m_config[charInts]["cHungerIncrement"] = "";
    m_config[charInts]["cFoodUnitValue"] = ""; // not in game files
    m_config[charInts]["cKeeperFoodUnitsEaten"] = "";
    m_config[charInts]["cNeededFood"] = "";
    m_config[charInts]["cNoFoodChange"] = "";
    m_config[charInts]["cInitialHappiness"] = "";
    m_config[charInts]["cMaxHits"] = "";
    m_config[charInts]["cPctHits"] = "";
    m_config[charInts]["cMaxEnergy"] = "";
    m_config[charInts]["cMaxDirty"] = ""; // not in game files
    m_config[charInts]["cMinDirty"] = ""; // not in game files
    m_config[charInts]["cSickChange"] = "";
    m_config[charInts]["cOtherAnimalSickChange"] = "";
    m_config[charInts]["cSickChance"] = "";
    m_config[charInts]["cSickRandomChance"] = ""; // not in game files
    m_config[charInts]["cCrowd"] = "";
    m_config[charInts]["cCrowdHappinessChange"] = "";
    m_config[charInts]["cZapHappinessChange"] = "";
    m_config[charInts]["cCaptivity"] = ""; // also cCaptivityCheck?
    m_config[charInts]["cReproductionChance"] = "";
    m_config[charInts]["cReproductionInterval"] = "";
    m_config[charInts]["cMatingType"] = "";
    m_config[charInts]["cOffspring"] = "";
    m_config[charInts]["cKeeperFrequency"] = "";
    m_config[charInts]["cNotEnoughKeepersChange"] = "";
    m_config[charInts]["cSocial"] = "";
    m_config[charInts]["cHabitatSize"] = ""; // also cSocialCheck?
    m_config[charInts]["cNumberAnimalsMin"] = "";
    m_config[charInts]["cNumberAnimalsMax"] = "";
    m_config[charInts]["cNumberMinChange"] = "";
    m_config[charInts]["cNumberMaxChange"] = "";
    m_config[charInts]["cHabitatPreference"] = "";
    m_config[charInts]["cBabyBornChange"] = "";
    m_config[charInts]["cEnergyIncrement"] = "";
    m_config[charInts]["cEnergyThreshold"] = "";
    m_config[charInts]["cDirtyIncrement"] = "";
    m_config[charInts]["cDirtyThreshold"] = "";
    m_config[charInts]["cSickTime"] = "";
    m_config[charInts]["cBabyToAdult"] = "";
    m_config[charInts]["cOtherFood"] = "";
    m_config[charInts]["cTreePref"] = "";
    m_config[charInts]["cRockPref"] = "";
    m_config[charInts]["cSpacePref"] = "";
    m_config[charInts]["cElevationPref"] = "";
    m_config[charInts]["cDepthMin"] = "";
    m_config[charInts]["cDepthMax"] = "";
    m_config[charInts]["cDepthChange"] = "";
    m_config[charInts]["cSalinityChange"] = "";
    m_config[charInts]["cSalinityHealthChange"] = "";
    m_config[charInts]["cHappyReproduceThreshold"] = "";
    m_config[charInts]["cBuildingUseChance"] = "";
    m_config[charInts]["cNoMateChange"] = "";
    m_config[charInts]["cTimeDeath"] = "";
    m_config[charInts]["cDeathChance"] = "";
    m_config[charInts]["cWaterNeeded"] = "";
    m_config[charInts]["cUnderwater"] = "";
    m_config[charInts]["cLandNeeded"] = "";
    m_config[charInts]["cEnterWaterChance"] = "";
    m_config[charInts]["cEnterTankChance"] = "";
    m_config[charInts]["cEnterLandChance"] = "";
    m_config[charInts]["cDrinkWaterChance"] = "";
    m_config[charInts]["cChaseAnimalChance"] = "";
    m_config[charInts]["cClimbsCliffs"] = "";
    m_config[charInts]["cBashStrength"] = "";
    m_config[charInts]["cAttractiveness"] = "";
    m_config[charInts]["cKeeperFoodType"] = "";
    m_config[charInts]["cIsClimber"] = "";
    m_config[charInts]["cIsJumper"] = "";
    m_config[charInts]["cSmallZoodoo"] = "";
    m_config[charInts]["cDinoZoodoo"] = "";
    m_config[charInts]["cGiantZoodoo"] = "";
    m_config[charInts]["cIsSpecialAnimal"] = "";
    m_config[charInts]["cNeedShelter"] = "";
    m_config[charInts]["cNeedToys"] = "";
    m_config[charInts]["cBabiesAttack"] = "";
}
